# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quantatel
email: mg@quantatel.com
description: >
  We are a group of dedicated young professionals who aims to make
     a difference in the mobile industry, by providing creative and dynamic solutions
     to the world to make it a digitalized space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.quantatel.com" # the base hostname & protocol for your site
twitter_username: Quantatel
github_username:  Quantatel

# Build settings
markdown: kramdown
